/* ======= оепелеммше =============*/
/* aGVAR.H = Global Variables Image-File. */
#ifndef _agvar_h
#define _agvar_h 1
/* ======= оепелеммше опнжеяянб ===*/
char P0V0;
char P0V1;
char P0V2;
char P0V3;
char P0V4;
char P0V5;
char P0V6;
char P0V7;
char P0V8;
char P0V9;
char P0V10[2];
char P0V11[2];
char P0V12[2];
char P0V13[2];
char P0V14[2];
char P0V15[2];
char P0V16[2];
char P0V17[2];
char P0V18[2];
/*======= Input Ports =============*/
char PI0;
char PI1;
char PI2;
char PI3;

/*======= Output Ports =============*/
char  PO0, FPO0;
char  PO1, FPO1;
#endif