/* ======= оепелеммше =============*/
/* aXVAR.H = Extern Variables Image-File. */
#ifndef _axvar_h
#define _axvar_h 1
/* ======= оепелеммше опнжеяянб ===*/
extern char P0V0;
extern char P0V1;
extern char P0V2;
extern char P0V3;
extern char P0V4;
extern char P0V5;
extern char P0V6;
extern char P0V7;
extern char P0V8;
extern char P0V9;
extern char P0V10[2];
extern char P0V11[2];
extern char P0V12[2];
extern char P0V13[2];
extern char P0V14[2];
extern char P0V15[2];
extern char P0V16[2];
extern char P0V17[2];
extern char P0V18[2];
/*======= Input Ports =============*/
extern char PI0;
extern char PI1;
extern char PI2;
extern char PI3;

/*======= Output Ports =============*/
extern char  PO0, FPO0;
extern char  PO1, FPO1;
#endif